# Generated by Django 4.2.5 on 2023-09-25 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Superadmin', 'Superadmin'), ('Admin', 'Admin'), ('Staff', 'Staff')], db_index=True, default='Admin', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Doctor', 'Doctor.'), ('Receptionalist', 'Receptionalist'), ('Nurse', 'Nurse'), ('Accountant', 'Accountant.'), ('Other', 'Other.')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_address',
                'verbose_name_plural': 'use_addresses',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=254)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
