# Generated by Django 4.2.5 on 2023-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_user_type_alter_user_designation_useraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(default='10', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Doctor', 'Doctor.'), ('Receptionalist', 'Receptionalist'), ('Nurse', 'Nurse'), ('Accountant', 'Accountant'), ('Other', 'Other'), ('Patient', 'Patient')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
