# Generated by Django 4.2.5 on 2023-10-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_created_by_user_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_address_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='user_address',
        ),
    ]
