# Generated by Django 4.2.5 on 2024-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_useraddress_city_alter_useraddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=50),
        ),
    ]
